title: NeuroRad
description: Appunti di neuroradiologia in italiano
theme: just-the-docs

url: https://gmadevs.github.io/neurorad

aux_links: # remove if you don't want this link to appear on your pages
  Codice sorgente: https://github.com/gmadevs/neurorad

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

color_scheme: dark

callouts: 
  attenzione: 
    title: Attenzione 
    color: red 

callouts: 
  tip: 
    title: Tip 
    color: green 

callouts: 
  nota: 
    title: Nota 
    color: blue